export const BRAND = {
  navy:     '#1F3864',
  gold:     '#D4AF37',
  emerald:  '#0E6E4B',
  charcoal: '#2B2B2B',
  midGrey:  '#7F7F7F',
  mildGrey: '#E6E6E6',
  offWhite: '#F7F7F5',
  lightGrey:'#D9D9D9',
};

export const CHART_COLORS = ['#4A7FBB','#BE4B48','#98B954','#8064A2','#6BAED6','#000000'];

export const THEMES = {
  institutional: {
    name:           'Default',
    bg:             BRAND.offWhite,
    surface:        '#FFFFFF',
    heroBg:         BRAND.navy,
    heroText:       '#FFFFFF',
    heroAccent:     BRAND.gold,
    tabActive:      BRAND.navy,
    tabActiveBorder:BRAND.gold,
    text:           BRAND.charcoal,
    muted:          BRAND.midGrey,
    border:         BRAND.mildGrey,
    accent:         BRAND.gold,
    buttonBg:       BRAND.navy,
    buttonText:     '#FFFFFF',
  },
  light: {
    name:           'Light',
    bg:             '#FFFFFF',
    surface:        '#FAFAFA',
    heroBg:         '#FFFFFF',
    heroText:       BRAND.navy,
    heroAccent:     BRAND.gold,
    tabActive:      BRAND.navy,
    tabActiveBorder:BRAND.navy,
    text:           BRAND.charcoal,
    muted:          BRAND.midGrey,
    border:         BRAND.mildGrey,
    accent:         BRAND.navy,
    buttonBg:       BRAND.navy,
    buttonText:     '#FFFFFF',
  },
  dark: {
    name:           'Dark',
    bg:             '#0F1724',
    surface:        '#1A2332',
    heroBg:         '#0A111D',
    heroText:       '#FFFFFF',
    heroAccent:     BRAND.gold,
    tabActive:      '#FFFFFF',
    tabActiveBorder:BRAND.gold,
    text:           '#F0F0F0',
    muted:          '#8B95A7',
    border:         '#2A3444',
    accent:         BRAND.gold,
    buttonBg:       BRAND.gold,
    buttonText:     BRAND.charcoal,
  },
};
